---
version: "3"

services:

  hc:
    container_name: hc
    build: ./hc
    volumes:
      - HC_STATIC:/healthchecks/static
      - HC_DB:/data
    env_file: hc/hc.env

  hc-web:
    container_name: hc-web
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - HC_STATIC:/healthchecks/static
    restart: always
    labels:
      - traefik.enable=true
      - "traefik.http.routers.hcweb.rule=Host(`healthcheck.bouni.de`)"
      - traefik.http.routers.hcweb.entrypoints=websecure
      - traefik.http.routers.hcweb.tls.certresolver=myhttpchallenge



  traefik:
    container_name: traefik
    image: traefik:v2.0
    restart: unless-stopped
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - --api.insecure=true 
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myhttpchallenge.acme.httpchallenge=true
      - --certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myhttpchallenge.acme.email=postmaster@mydomain.com
      - --certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt




        #  traefik:
        #    container_name: traefik
        #    image: traefik:1.7
        #    command: --api --docker
        #    restart: always
        #    ports:
        #      - 80:80
        #      - 443:443
        #      - 127.0.0.1:8080:8080
        #    volumes:
        #      - /var/run/docker.sock:/var/run/docker.sock
        #      - ./traefik/traefik.yaml:/traefik.yaml
        #      - ./traefik/acme.json:/acme.json
        #    labels:
        #      - traefik.enable=false

volumes:
  HC_STATIC: {}
  HC_DB: {}
