---
version: "3"

services:

  healthchecks:
    container_name: healthchecks
    build: ./healthchecks
    volumes:
      - HC_STATIC:/healthchecks/static
      - ./data:/data
    env_file: healthchecks/healthchecks.env

  healthchecks-nginx:
    container_name: healthchecks-nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - HC_STATIC:/healthchecks/static
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.healthchecks.rule=Host(`healthcheck.bouni.de`)
      - traefik.http.routers.healthchecks.entrypoints=websecure
      - traefik.http.routers.healthchecks.tls.certresolver=myhttpchallenge

  traefik-reverse-proxy:
    container_name: traefik-reverse-proxy
    image: traefik:v2.0
    restart: unless-stopped
    command: 
      - --api.insecure=true 
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myhttpchallenge.acme.httpchallenge=true
      - --certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myhttpchallenge.acme.email=postmaster@mydomain.com
      - --certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt

volumes:
  HC_STATIC: {}
